par(mfrow = c(2,1))
a<-runif(100)
b<-runif(100)
plot(a,b,col="red", xlim=c(0,1), ylim=c(0,1), xlab="ascissa", ylab="ordinata", lwd=2)
plot(b,a,col="blue", xlim=c(0,1), ylim=c(0,1), xlab="ascissa", ylab="ordinata", lwd=2)
Sys.sleep(1)
d<-runif(100)
e<-runif(100)
plot(c(a,d),c(b,e),col="red", xlim=c(0,1), ylim=c(0,1), xlab="ascissa", ylab="ordinata", lwd=2)
plot(c(b,e),c(a,d),col="blue", xlim=c(0,1), ylim=c(0,1), xlab="ascissa", ylab="ordinata", lwd=2)
Sys.sleep(1)
g<-runif(100)
h<-runif(100)
plot(c(a,d,g),c(b,e,h),col="red", xlim=c(0,1), ylim=c(0,1), xlab="ascissa", ylab="ordinata", lwd=2)
plot(c(b,e,h),c(a,d,g),col="blue", xlim=c(0,1), ylim=c(0,1), xlab="ascissa", ylab="ordinata", lwd=2)
Sys.sleep(1)
i<-runif(100)
l<-runif(100)
plot(c(a,d,g,i),c(b,e,h,l),col="red", xlim=c(0,1), ylim=c(0,1), xlab="ascissa", ylab="ordinata", lwd=2)
plot(c(b,e,h,l),c(a,d,g,i),col="blue", xlim=c(0,1), ylim=c(0,1), xlab="ascissa", ylab="ordinata", lwd=2)

